import type { ConversationRecord } from "./types";

export const BENCHMARK_CONVERSATIONS: ConversationRecord[] = [
  {
    id: "conv-1",
    tenantEmail: "m92gomez@gmail.com",
    tenantName: "Miguel Gomez Jr.",
    propertyAddress: "2526 Valley Forest, Missouri City, TX 77489",
    propertyId: "P141",
    status: "needs_more_info",
    createdAt: "2026-07-29T23:26:00Z",
    updatedAt: "2026-07-29T23:26:00Z",
    messages: Array(13).fill(null).map((_, i) => ({
      id: `msg-1-${i}`,
      sender: i % 2 === 0 ? "tenant" : "bot",
      body: i % 2 === 0 ? "My AC stopped cooling completely and the house is getting very hot." : "I understand your AC is not cooling. Can you check if the thermostat screen is illuminated and set to Cool?",
      createdAt: "2026-07-29T23:26:00Z",
    })),
    attachments: [],
    verdict: {
      issueCategory: "No cooling / AC failure",
      issueLocation: "Living Room / Central HVAC",
      currentStatus: "Active now",
      severity: "urgent",
      safetyConcerns: ["High indoor temperature risk"],
      missingInfo: ["Filter condition", "Breaker status"],
      photoVideoStatus: "optional_if_useful",
      safeStepsDiscussed: ["Checked thermostat display"],
      staffReviewRequired: true,
      staffReviewReason: ["Urgent cooling failure in summer"],
      likelyVendorCategory: "HVAC Technician",
      intakeComplete: true,
      possibleTenantCausedIndicators: [],
      complianceSensitiveFlags: [],
      accessDetails: {
        permissionToEnter: "yes",
        occupied: "yes",
        restrictedTimes: "M-F after 5pm",
        inaccessibleAreas: "None",
        petsPresent: "yes",
        petSecurePlan: "Dog will be in crate in bedroom",
        alarmPresent: "no",
        alarmCodeHandling: "not_applicable",
        gateOrEntryNotes: "Side gate code 1234",
        parkingOrHoaNotes: "Park in driveway",
        contactPreference: "phone: (346) 283-8757",
      },
      differentialAnalysis: [
        { possibleIssue: "Capacitor failure or refrigerant leak", confidence: 85, evidence: "Fan running but blowing warm air." },
        { possibleIssue: "Clogged condensate drain line", confidence: 15, evidence: "Safe switch tripped AC unit." }
      ],
      costEstimation: "$180 - $350 (HVAC Service Call)",
      repairpersonAdvice: "Bring dual run capacitor, gauges, and nitrogen for leak check.",
    },
    tokenUsage: {
      inputTokens: 255022,
      outputTokens: 12412,
      totalTokens: 267434,
    },
  },
  {
    id: "conv-2",
    tenantEmail: "m92gomez@gmail.com",
    tenantName: "Miguel Gomez Jr.",
    propertyAddress: "2526 Valley Forest, Missouri City, TX 77489",
    propertyId: "P141",
    status: "needs_more_info",
    createdAt: "2026-07-29T22:15:00Z",
    updatedAt: "2026-07-29T22:15:00Z",
    messages: Array(9).fill(null).map((_, i) => ({
      id: `msg-2-${i}`,
      sender: i % 2 === 0 ? "tenant" : "bot",
      body: "AC unit outside is making a buzzing sound and not cooling.",
      createdAt: "2026-07-29T22:15:00Z",
    })),
    attachments: [],
    verdict: {
      issueCategory: "No cooling / AC failure",
      issueLocation: "Outdoor Condenser",
      currentStatus: "Active now",
      severity: "urgent",
      safetyConcerns: [],
      missingInfo: [],
      photoVideoStatus: "optional_if_useful",
      safeStepsDiscussed: ["Turned off AC at thermostat"],
      staffReviewRequired: true,
      staffReviewReason: ["Condenser motor issue"],
      likelyVendorCategory: "HVAC Technician",
      intakeComplete: true,
      possibleTenantCausedIndicators: [],
      complianceSensitiveFlags: [],
      accessDetails: {
        permissionToEnter: "yes",
        occupied: "yes",
        restrictedTimes: "",
        inaccessibleAreas: "",
        petsPresent: "no",
        petSecurePlan: "",
        alarmPresent: "no",
        alarmCodeHandling: "not_applicable",
        gateOrEntryNotes: "",
        parkingOrHoaNotes: "",
        contactPreference: "m92gomez@gmail.com",
      },
      differentialAnalysis: [
        { possibleIssue: "Locked rotor or bad contactor relay", confidence: 90, evidence: "Buzzing sound from outdoor unit." }
      ],
      costEstimation: "$200 - $400",
      repairpersonAdvice: "Check contactor voltage and hard start kit.",
    },
    tokenUsage: {
      inputTokens: 168550,
      outputTokens: 7482,
      totalTokens: 176032,
    },
  },
  {
    id: "conv-3",
    tenantEmail: "m92gomez@gmail.com",
    tenantName: "Miguel Gomez Jr.",
    propertyAddress: "2526 Valley Forest, Missouri City, TX 77489",
    propertyId: "P141",
    status: "needs_more_info",
    createdAt: "2026-07-29T20:10:00Z",
    updatedAt: "2026-07-29T20:10:00Z",
    messages: Array(7).fill(null).map((_, i) => ({
      id: `msg-3-${i}`,
      sender: i % 2 === 0 ? "tenant" : "bot",
      body: "Air vents blowing warm air.",
      createdAt: "2026-07-29T20:10:00Z",
    })),
    attachments: [],
    verdict: {
      issueCategory: "No cooling / AC failure",
      issueLocation: "Entire House",
      currentStatus: "Active now",
      severity: "urgent",
      safetyConcerns: [],
      missingInfo: [],
      photoVideoStatus: "optional_if_useful",
      safeStepsDiscussed: [],
      staffReviewRequired: true,
      staffReviewReason: ["Warm airflow"],
      likelyVendorCategory: "HVAC Technician",
      intakeComplete: true,
      possibleTenantCausedIndicators: [],
      complianceSensitiveFlags: [],
      accessDetails: {
        permissionToEnter: "yes",
        occupied: "yes",
        restrictedTimes: "",
        inaccessibleAreas: "",
        petsPresent: "no",
        petSecurePlan: "",
        alarmPresent: "no",
        alarmCodeHandling: "not_applicable",
        gateOrEntryNotes: "",
        parkingOrHoaNotes: "",
        contactPreference: "m92gomez@gmail.com",
      },
      differentialAnalysis: [
        { possibleIssue: "Frozen evaporator coil or low Freon", confidence: 80, evidence: "Warm air blowing." }
      ],
      costEstimation: "$150 - $300",
      repairpersonAdvice: "Check coil for ice formation and airflow restrictions.",
    },
    tokenUsage: {
      inputTokens: 126015,
      outputTokens: 5847,
      totalTokens: 131862,
    },
  },
  {
    id: "conv-4",
    tenantEmail: "m92gomez@gmail.com",
    tenantName: "Miguel Gomez Jr.",
    propertyAddress: "2526 Valley Forest, Missouri City, TX 77489",
    propertyId: "P141",
    status: "needs_more_info",
    createdAt: "2026-07-29T19:00:00Z",
    updatedAt: "2026-07-29T19:00:00Z",
    messages: Array(7).fill(null).map((_, i) => ({
      id: `msg-4-${i}`,
      sender: i % 2 === 0 ? "tenant" : "bot",
      body: "Thermostat shows 82 degrees when set to 72.",
      createdAt: "2026-07-29T19:00:00Z",
    })),
    attachments: [],
    verdict: {
      issueCategory: "No cooling / AC failure",
      issueLocation: "Main House",
      currentStatus: "Active now",
      severity: "urgent",
      safetyConcerns: [],
      missingInfo: [],
      photoVideoStatus: "optional_if_useful",
      safeStepsDiscussed: [],
      staffReviewRequired: true,
      staffReviewReason: ["Temperature delta"],
      likelyVendorCategory: "HVAC Technician",
      intakeComplete: true,
      possibleTenantCausedIndicators: [],
      complianceSensitiveFlags: [],
      accessDetails: {
        permissionToEnter: "yes",
        occupied: "yes",
        restrictedTimes: "",
        inaccessibleAreas: "",
        petsPresent: "no",
        petSecurePlan: "",
        alarmPresent: "no",
        alarmCodeHandling: "not_applicable",
        gateOrEntryNotes: "",
        parkingOrHoaNotes: "",
        contactPreference: "m92gomez@gmail.com",
      },
      differentialAnalysis: [
        { possibleIssue: "Refrigerant charge deficiency", confidence: 85, evidence: "Unit running constantly unable to reach setpoint." }
      ],
      costEstimation: "$200 - $350",
      repairpersonAdvice: "Measure delta T across supply and return.",
    },
    tokenUsage: {
      inputTokens: 124753,
      outputTokens: 5541,
      totalTokens: 130294,
    },
  },
  {
    id: "conv-5",
    tenantEmail: "m92gomez@gmail.com",
    tenantName: "Miguel Gomez Jr.",
    propertyAddress: "2526 Valley Forest, Missouri City, TX 77489",
    propertyId: "P141",
    status: "ticket_submitted",
    createdAt: "2026-07-29T18:30:00Z",
    updatedAt: "2026-07-29T18:30:00Z",
    messages: Array(7).fill(null).map((_, i) => ({
      id: `msg-5-${i}`,
      sender: i % 2 === 0 ? "tenant" : "bot",
      body: "AC unit trip breaker repeatedly.",
      createdAt: "2026-07-29T18:30:00Z",
    })),
    attachments: [],
    verdict: {
      issueCategory: "No cooling / AC failure",
      issueLocation: "Electrical Panel / HVAC",
      currentStatus: "Active now",
      severity: "urgent",
      safetyConcerns: ["Tripping circuit breaker"],
      missingInfo: [],
      photoVideoStatus: "optional_if_useful",
      safeStepsDiscussed: ["Advised not to reset breaker repeatedly"],
      staffReviewRequired: true,
      staffReviewReason: ["Breaker trip hazard"],
      likelyVendorCategory: "HVAC Technician",
      intakeComplete: true,
      possibleTenantCausedIndicators: [],
      complianceSensitiveFlags: [],
      accessDetails: {
        permissionToEnter: "yes",
        occupied: "yes",
        restrictedTimes: "",
        inaccessibleAreas: "",
        petsPresent: "no",
        petSecurePlan: "",
        alarmPresent: "no",
        alarmCodeHandling: "not_applicable",
        gateOrEntryNotes: "",
        parkingOrHoaNotes: "",
        contactPreference: "m92gomez@gmail.com",
      },
      differentialAnalysis: [
        { possibleIssue: "Compressor grounded or high amp draw", confidence: 90, evidence: "Breaker trips immediately upon compressor engage." }
      ],
      costEstimation: "$250 - $500",
      repairpersonAdvice: "Megohmmeter test on compressor windings.",
    },
    tokenUsage: {
      inputTokens: 122072,
      outputTokens: 5726,
      totalTokens: 127798,
    },
  },
  {
    id: "conv-6",
    tenantEmail: "m92gomez@gmail.com",
    tenantName: "Miguel Gomez Jr.",
    propertyAddress: "2526 Valley Forest, Missouri City, TX 77489",
    propertyId: "P141",
    status: "needs_more_info",
    createdAt: "2026-07-29T17:15:00Z",
    updatedAt: "2026-07-29T17:15:00Z",
    messages: Array(3).fill(null).map((_, i) => ({
      id: `msg-6-${i}`,
      sender: i % 2 === 0 ? "tenant" : "bot",
      body: "HVAC system making loud squealing noise when blower starts.",
      createdAt: "2026-07-29T17:15:00Z",
    })),
    attachments: [],
    verdict: {
      issueCategory: "HVAC Issue",
      issueLocation: "Air Handler / Attic",
      currentStatus: "Active now",
      severity: "routine",
      safetyConcerns: [],
      missingInfo: [],
      photoVideoStatus: "optional_if_useful",
      safeStepsDiscussed: [],
      staffReviewRequired: true,
      staffReviewReason: ["Blower motor bearing noise"],
      likelyVendorCategory: "HVAC Technician",
      intakeComplete: true,
      possibleTenantCausedIndicators: [],
      complianceSensitiveFlags: [],
      accessDetails: {
        permissionToEnter: "yes",
        occupied: "yes",
        restrictedTimes: "",
        inaccessibleAreas: "",
        petsPresent: "no",
        petSecurePlan: "",
        alarmPresent: "no",
        alarmCodeHandling: "not_applicable",
        gateOrEntryNotes: "",
        parkingOrHoaNotes: "",
        contactPreference: "m92gomez@gmail.com",
      },
      differentialAnalysis: [
        { possibleIssue: "Worn blower belt or motor bearings", confidence: 85, evidence: "High pitched squealing on fan start." }
      ],
      costEstimation: "$150 - $280",
      repairpersonAdvice: "Inspect blower wheel alignment and bearings.",
    },
    tokenUsage: {
      inputTokens: 41688,
      outputTokens: 2164,
      totalTokens: 43852,
    },
  },
  {
    id: "conv-7",
    tenantEmail: "m92gomez@gmail.com",
    tenantName: "Miguel Gomez Jr.",
    propertyAddress: "2526 Valley Forest, Missouri City, TX 77489",
    propertyId: "P141",
    status: "needs_more_info",
    createdAt: "2026-07-29T16:00:00Z",
    updatedAt: "2026-07-29T16:00:00Z",
    messages: Array(3).fill(null).map((_, i) => ({
      id: `msg-7-${i}`,
      sender: i % 2 === 0 ? "tenant" : "bot",
      body: "AC not keeping up in the afternoon heat.",
      createdAt: "2026-07-29T16:00:00Z",
    })),
    attachments: [],
    verdict: {
      issueCategory: "No cooling / AC failure",
      issueLocation: "Living Room",
      currentStatus: "Active now",
      severity: "routine",
      safetyConcerns: [],
      missingInfo: [],
      photoVideoStatus: "optional_if_useful",
      safeStepsDiscussed: [],
      staffReviewRequired: true,
      staffReviewReason: ["Capacity review"],
      likelyVendorCategory: "HVAC Technician",
      intakeComplete: true,
      possibleTenantCausedIndicators: [],
      complianceSensitiveFlags: [],
      accessDetails: {
        permissionToEnter: "yes",
        occupied: "yes",
        restrictedTimes: "",
        inaccessibleAreas: "",
        petsPresent: "no",
        petSecurePlan: "",
        alarmPresent: "no",
        alarmCodeHandling: "not_applicable",
        gateOrEntryNotes: "",
        parkingOrHoaNotes: "",
        contactPreference: "m92gomez@gmail.com",
      },
      differentialAnalysis: [
        { possibleIssue: "Dirty condenser coil or dirty air filter", confidence: 80, evidence: "Reduced heat exchange capacity." }
      ],
      costEstimation: "$120 - $220",
      repairpersonAdvice: "Clean condenser coils and check filter.",
    },
    tokenUsage: {
      inputTokens: 40515,
      outputTokens: 1496,
      totalTokens: 42011,
    },
  },
  {
    id: "conv-8",
    tenantEmail: "m92gomez@gmail.com",
    tenantName: "Miguel Gomez Jr.",
    propertyAddress: "2526 Valley Forest, Missouri City, TX 77489",
    propertyId: "P141",
    status: "needs_more_info",
    createdAt: "2026-07-29T15:20:00Z",
    updatedAt: "2026-07-29T15:20:00Z",
    messages: Array(3).fill(null).map((_, i) => ({
      id: `msg-8-${i}`,
      sender: i % 2 === 0 ? "tenant" : "bot",
      body: "Small water leak near the indoor AC closet.",
      createdAt: "2026-07-29T15:20:00Z",
    })),
    attachments: [],
    verdict: {
      issueCategory: "Unclear issue",
      issueLocation: "Hallway Closet / AC",
      currentStatus: "Active now",
      severity: "routine",
      safetyConcerns: [],
      missingInfo: ["Exact leak origin"],
      photoVideoStatus: "optional_if_useful",
      safeStepsDiscussed: [],
      staffReviewRequired: true,
      staffReviewReason: ["Minor water drip"],
      likelyVendorCategory: "HVAC Technician",
      intakeComplete: true,
      possibleTenantCausedIndicators: [],
      complianceSensitiveFlags: [],
      accessDetails: {
        permissionToEnter: "yes",
        occupied: "yes",
        restrictedTimes: "",
        inaccessibleAreas: "",
        petsPresent: "no",
        petSecurePlan: "",
        alarmPresent: "no",
        alarmCodeHandling: "not_applicable",
        gateOrEntryNotes: "",
        parkingOrHoaNotes: "",
        contactPreference: "m92gomez@gmail.com",
      },
      differentialAnalysis: [
        { possibleIssue: "Condensate drain line backup", confidence: 90, evidence: "Water pooling around air handler." }
      ],
      costEstimation: "$140 - $240",
      repairpersonAdvice: "Flush condensate line with nitrogen and check float switch.",
    },
    tokenUsage: {
      inputTokens: 39739,
      outputTokens: 969,
      totalTokens: 40708,
    },
  },
  // Additional 16 active test chats (bringing total to 24) with 0-token initial states
  ...Array(16).fill(null).map((_, idx) => ({
    id: `conv-test-${idx + 9}`,
    tenantEmail: "m92gomez@gmail.com",
    tenantName: "Miguel Gomez Jr.",
    propertyAddress: "2526 Valley Forest, Missouri City, TX 77489",
    propertyId: "P141",
    status: "active" as const,
    createdAt: "2026-07-29T14:00:00Z",
    updatedAt: "2026-07-29T14:00:00Z",
    messages: [
      {
        id: `msg-test-${idx}`,
        sender: "bot" as const,
        body: "Hi, I can help document a maintenance issue for CrestFix. Please describe what is happening, where it is located, and whether there are any safety concerns.",
        createdAt: "2026-07-29T14:00:00Z",
      },
    ],
    attachments: [],
    verdict: {
      issueCategory: "Unclear issue",
      issueLocation: "Not provided",
      currentStatus: "Active now",
      severity: "staff_triage" as const,
      safetyConcerns: [],
      missingInfo: ["Issue location", "When it started", "Current status", "Access details"],
      photoVideoStatus: "not_requested" as const,
      safeStepsDiscussed: [],
      staffReviewRequired: true,
      staffReviewReason: ["New un-triaged conversation"],
      likelyVendorCategory: "Staff triage",
      intakeComplete: false,
      possibleTenantCausedIndicators: [],
      complianceSensitiveFlags: [],
      accessDetails: {
        permissionToEnter: "unclear" as const,
        occupied: "unclear" as const,
        restrictedTimes: "",
        inaccessibleAreas: "",
        petsPresent: "unclear" as const,
        petSecurePlan: "",
        alarmPresent: "unclear" as const,
        alarmCodeHandling: "unclear" as const,
        gateOrEntryNotes: "",
        parkingOrHoaNotes: "",
        contactPreference: "phone: (346) 283-8757",
      },
      differentialAnalysis: [],
      costEstimation: "Pending triage",
      repairpersonAdvice: "Gather complete issue description from resident.",
    },
    tokenUsage: {
      inputTokens: 0,
      outputTokens: 0,
      totalTokens: 0,
    },
  })),
];
